# Generated by Django 4.0.5 on 2022-06-22 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=50, verbose_name='Marke')),
                ('modelis', models.CharField(max_length=100, verbose_name='Modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.TextField(verbose_name='Valstybinis nr')),
                ('vin_kodas', models.CharField(max_length=17, verbose_name='VIN kodas')),
                ('klientas', models.CharField(max_length=100, verbose_name='Klientas')),
                ('automobilio_modelis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servisas.automobilio_modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=20, verbose_name='Paslaugos pavadinimas')),
                ('kaina', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uszakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='Data')),
                ('suma', models.IntegerField(verbose_name='Suma')),
                ('automobilis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servisas.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymo_eilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaina', models.IntegerField()),
                ('paslaugos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servisas.paslauga')),
                ('uzsakymo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servisas.uszakymas')),
            ],
        ),
    ]
