# Generated by Django 4.0.5 on 2022-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uszakymas',
            new_name='Uzsakymas',
        ),
        migrations.AlterModelOptions(
            name='automobilio_modelis',
            options={'verbose_name_plural': 'Automobilio modelis'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name_plural': 'Automobilis'},
        ),
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name_plural': 'Paslauga'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name_plural': 'Uzsakymas'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymo_eilute',
            options={'verbose_name_plural': 'Uzsakymo eilute'},
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='valstybinis_nr',
            field=models.CharField(max_length=10, verbose_name='Valstybinis nr'),
        ),
    ]
