# Generated by Django 4.0.5 on 2022-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0002_rename_uszakymas_uzsakymas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymas',
            name='automobilis_id',
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='automobilis_id',
            field=models.ManyToManyField(null=True, to='servisas.automobilis'),
        ),
    ]
