# Generated by Django 4.0.5 on 2022-06-22 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0003_remove_uzsakymas_automobilis_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymas',
            name='automobilis_id',
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='automobilis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servisas.automobilis'),
        ),
    ]
