# Generated by Django 4.0.5 on 2022-06-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0004_remove_uzsakymas_automobilis_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='suma',
            field=models.FloatField(verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='kaina',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uzsakymo_eilute',
            name='uzsakymo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servisas.uzsakymas'),
        ),
    ]
