# Generated by Django 4.0.5 on 2022-06-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0005_alter_uzsakymas_suma_alter_uzsakymo_eilute_kaina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Priimta'), ('i', 'Vykdoma'), ('d', 'Pabaigta'), ('c', 'Atmesta')], default='a', help_text='Statusas', max_length=1),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='valstybinis_nr',
            field=models.CharField(help_text='Valstybinis', max_length=10, verbose_name='Valstybinis nr'),
        ),
    ]
