# Generated by Django 4.0.5 on 2022-06-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servisas', '0006_uzsakymas_status_alter_automobilis_valstybinis_nr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilio_modelis',
            options={'verbose_name': 'Automobilio modelis', 'verbose_name_plural': 'Automobiliu modeliai'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name': 'Uzsakymas', 'verbose_name_plural': 'Uzsakymai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymo_eilute',
            options={'verbose_name': 'Uzsakymo eilute', 'verbose_name_plural': 'Uzsakymu eilutes'},
        ),
    ]
